# Generated by Django 3.1.2 on 2021-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=50)),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(choices=[('high', 'high'), ('low', 'low'), ('normal', 'normal')], max_length=50)),
                ('comment', models.TextField(max_length=100)),
                ('breast_pelvic', models.CharField(max_length=50)),
                ('baby_HeartBeart_rate', models.CharField(max_length=50)),
                ('cervical_exam', models.CharField(max_length=50)),
                ('sti', models.CharField(max_length=50)),
                ('Hiv_result', models.CharField(choices=[('negative', 'negative'), ('positive', 'positive')], max_length=50)),
                ('Rh_factor', models.CharField(max_length=50)),
                ('Diabetes', models.CharField(max_length=50)),
                ('Hepatitis_B', models.CharField(max_length=50)),
                ('pregnancy_test', models.CharField(choices=[('negative', 'negative'), ('positive', 'positive')], max_length=50)),
            ],
        ),
    ]
