# Generated by Django 3.1.2 on 2021-08-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalrecord',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
