# Generated by Django 3.1.2 on 2021-08-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_care', '0002_auto_20210802_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalrecord',
            name='Hiv_result',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maternalrecord',
            name='blood_pressure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maternalrecord',
            name='pregnancy_test',
            field=models.CharField(max_length=50),
        ),
    ]
